name: inverse-modeling
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - jax
  - pytorch
  - cpuonly
  - scikit-learn
  - matplotlib
  - jupyter
  - nbconvert
  - ipykernel
  - gmsh
  - python-gmsh
  - petsc4py
  - fenics-basix
  - pip
  - pip:
    - plotly
    - seaborn
    - pyfiglet
    - meshio
    - digital_twinning
    - uncertain_variables
    - git+https://github.com/deepmodeling/jax-fem.git
